name: .NET + Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish -c RELEASE -r debian-arm64 --no-self-contained
    - name: Upload DimBot executable
      uses: actions/upload-artifact@v2
      with:
        name: DimBot
        path: bin/Release/net6.0/debian-arm64/publish/DimBot
    - name: Upload DimBot library
      uses: actions/upload-artifact@v2
      with:
        name: DimBot.dll
        path: bin/Release/net6.0/debian-arm64/publish/DimBot.dll