name: .NET + Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r linux-arm64 --self-contained false
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: DimBot
        path: |
          DimBot-Helenite/bin/Debug/net6.0/linux-arm64/publish/DimBot
          DimBot-Helenite/bin/Debug/net6.0/linux-arm64/publish/*.dll